FROM docker.elastic.co/elasticsearch/elasticsearch:7.12.0

#ENV ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"

#RUN elasticsearch-plugin install x-pack

#CMD ["-E", "http.host=0.0.0.0", "-E", "transport.host=127.0.0.1", "-E", "discovery.zen.minimum_master_nodes=1"]