version: '2.2'
services:
  elasticsearch:
    build: ../images/elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms12g -Xms12g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
   
  kibana:
    build: ../images/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  backend-api:
    build: ../images/backend-api
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch      
volumes:
  es-data01:
    driver: local
    #external: true

